# NPCPlugin Configuration

# NPC Behavior Settings
behavior:
  interact_radius: 4 # Radius within which NPCs can interact with blocks (default: 4 blocks)
  mine_radius: 4 # Radius within which NPCs can mine blocks (default: 4 blocks)
  build_radius: 10 # Radius within which NPCs can build structures (default: 10 blocks)
  attack_radius: 10 # Radius within which NPCs can attack mobs and players (default: 10 blocks)
  attack_damage: 2.0 # Damage dealt by NPCs when attacking mobs or players (default: 2.0 hearts)
  health: 100.0 # Health of NPCs (default: 100.0 hearts)
  heal_rate: 1.0 # Rate at which NPCs heal themselves per second (default: 1.0 heart/second)
  follow_distance: 5 # Maximum distance between NPC and owner for following (default: 5 blocks)
  walk_speed: 0.2 # Walk speed of NPCs (default: 0.2)
  run_speed: 0.4 # Run speed of NPCs (default: 0.4)
  
# NPC Appearance Settings
appearance:
  name_tag: "&bNPC Bot" # Custom name tag displayed above NPCs' heads (default: "&bNPC Bot")
  owner_tag: true # Whether to display the owner's name next to the NPC's name (default: true)
